### ISSUE TITLE
Just: Thank you....

### ISSUE THREAD

**Issue by evicent** [giovannibenussi/use-persisted-state-hook#1]
No issues so far...only thank you for this useful hook!

**Comment by giovannibenussi** [comment]
Hi @evicent! Glad that you liked this 😄
It’s good to know that people like this project 🙌

Even though the core of the project is done, there are a few ideas that I’d like to do:
- Reduce bundle size.
- Improve runtime performance.
- Refactor test suite.
- Automatically run test suite after every change.

Everyone is welcome to collaborate and learn together here and [on my personal Twitter account](https://twitter.com/giovannibenussi) 👋
