### ISSUE TITLE
update react peer/dev dependency

### ISSUE THREAD

**Issue by JohnRDOrazio** [giovannibenussi/use-persisted-state-hook#5]
I'm seeing that in the package.json, there is a peer dependency for React `<= 16.8.0`. Is this perhaps a mistake? Should it be `>=16.18.0`? I updated my project to React 17, and everything still seems to work fine, I just get the warning of an incorrect peer dependency.

https://github.com/giovannibenussi/use-persisted-state-hook/blob/31cceaa211a37234febd1e68a7bcc11c61cd05ee/package.json#L35

**Comment by giovannibenussi** [comment]
Good catch! That makes sense, I just tested your suggestion with [Semver check](https://jubianchi.github.io/semver-check/#/%3E%3D16.8.0/17.0.0), and looks good.

Would you like to contribute with a fix for it? Otherwise, I could do it :-)
