### ISSUE TITLE
source map is missing from distributed bundle

### ISSUE THREAD

**Issue by JohnRDOrazio** [giovannibenussi/use-persisted-state-hook#7]
when adding the package to a project, no source map "index.js.map" is found in the `dist` folder. And yet, if I build it myself, i see that the source map is created by `microbundle` with `yarn build`. Perhaps you are explicitly removing it from the final package? This generates a warning for any project using the package:

> Compiled with warnings.
> 
> Failed to parse source map from '/home/.../node_modules/use-persisted-state-hook/dist/index.js.map' file: Error: ENOENT: no such file or directory, open '/home/.../node_modules/use-persisted-state-hook/dist/index.js.map'
> 
> Search for the keywords to learn more about each warning.
> To ignore, add // eslint-disable-next-line to the line before.
> 
> WARNING in ./node_modules/use-persisted-state-hook/dist/index.js
> Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
> Failed to parse source map from '/home/.../node_modules/use-persisted-state-hook/dist/index.js.map' file: Error: ENOENT: no such file or directory, open '/home/.../node_modules/use-persisted-state-hook/dist/index.js.map'
> 
> webpack compiled with 1 warning
>

**Comment by giovannibenussi** [comment]
Hi! Thanks for reporting this and sorry for the late response.

After a while, I figured out how to make this work by adding the `files` entry in the `package.json` file:

```json
"files": [
  "dist/*"
]
```

I needed to remove the `dist` folder from `.gitignore` to make it work.

Looks good now:

```bash
ls node_modules/use-persisted-state-hook/dist
index.esm.js        index.js            index.modern.js     index.umd.js
index.esm.js.map    index.js.map        index.modern.js.map index.umd.js.map
```

**Comment by JohnRDOrazio** [comment]
Thank you! I have updated to the latest package and the warning is now gone.
